### ISSUE TITLE
Header buttons not showing on Web (Next.js)

### ISSUE THREAD

**Issue by MustafaAlsihati** [farhoudshapouran/react-native-ui-datepicker#11]
Hello! 

I'm using React Native (solito) running on web, but it seems that the header buttons are not showing on web, I tried to find the reason it seems that the images are not loaded, maybe it's an issue with next.js only I'm not sure, but maybe if we can add a custom buttons will solve it? or use Svg icon instead of an image?

Here's a screenshot for web:
![image](https://github.com/farhoudshapouran/react-native-ui-datepicker/assets/51824138/9fcad202-f6d5-4c2e-8a62-93f1cc06df35)

This is in Android (working fine also on iOS):
![image](https://github.com/farhoudshapouran/react-native-ui-datepicker/assets/51824138/83889358-3a92-43de-889c-fe115f07d35d)

Other than that it's a great work, working like charm in both Android & iOS! 🌹

**Comment by farhoudshapouran** [comment]
Hello @MustafaAlsihati, thank you for reporting this, I am working on it to enable adding custom icon buttons.

**Comment by farhoudshapouran** [comment]
Now we can define custom icons for prev and next buttons with these options:
```
buttonPrevIcon
buttonNextIcon
```

**Comment by MustafaAlsihati** [comment]
> Now we can define custom icons for prev and next buttons with these options:
> 
> ```
> buttonPrevIcon
> buttonNextIcon
> ```

@farhoudshapouran That's awesome! Thanks 🌹
