### ISSUE TITLE
Add a style prop to the Calendar Container 

### ISSUE THREAD

**Issue by NightClover-code** [farhoudshapouran/react-native-ui-datepicker#112]
There is currently no way to style the container that holds the date numbers, for example, I'd like to remove this extra bottom margin (see image).

![image](https://github.com/user-attachments/assets/dd51c8c0-158b-4087-8abe-80cb093f002e)

- This could be done by adding extra styles as a prop to the `Calendar.tsx` component stylesheet.

**Comment by snursultan** [comment]
Hi @NightClover-code 

I believe this space was left there for a possible 6th week. In the screenshot you attached, September 2024 has only 5 weeks, but June 2024 will have 6 weeks in this view. 

Try to change the month and see, that sometimes we have 6 weeks in a month and this space is needed so the calendar will have a "static" height, in a sense that doesn't change depending on the month.

**Comment by NightClover-code** [comment]
Hey @snursultan, thanks for the reply! That totally makes sense, thanks for pointing it out. I think it'd be better to set the height dynamically based on those date rows, don't you think? I will close this issue now as your comment clarifies everything.

**Comment by snursultan** [comment]
Hi @NightClover-code, I am glad that my answer helped. 

Maybe the dynamic height option could be helpful. Just to inform: I was happy with the static one in my case, since I don't want my layout change because of the calendar size changing.

Have a great day!
