### ISSUE TITLE
Can't remove currentDay color

### ISSUE THREAD

**Issue by JoshDunnDev** [farhoudshapouran/react-native-ui-datepicker#12]
I tried using styling to do this but seems like that this can't be done. Is it possible to add an option that would allow you to not highlight the currentDay (today)?

![Screenshot 2023-10-25 at 11 26 01 AM](https://github.com/farhoudshapouran/react-native-ui-datepicker/assets/22648574/4ef90527-eab4-4662-9929-f91251a3ac5e)

**Comment by farhoudshapouran** [comment]
Hello, @JoshDunnDev thank you for reporting this issue, we can add options to style both current and selected days independently, I am working on some new features and consider these options also.

**Comment by JoshDunnDev** [comment]
Ok great thank you!

**Comment by farhoudshapouran** [comment]
Now we can style today's item with these 2 options:
```
todayContainerStyle
todayTextStyle
```

**Comment by sayan-avantai** [comment]
> Now we can style today's item with these 2 options:
> 
> ```
> todayContainerStyle
> todayTextStyle
> ```

This is not working:
```
todayTextStyle: {color: 'red'},

todayContainerStyle: {
borderColor: 'red',
borderWidth: 1,
backgroundColor:'red'
},
```

only this is working:

```
 today: {
borderColor: colors.calendarSelectionColor,
borderWidth: 1,
borderRadius: 28,
},
 today_label: {
color: 'yellow',
},
```
