### ISSUE TITLE
Clicking on a date doesn't select it, but the onChange event is triggered

### ISSUE THREAD

**Issue by nerdroid23** [farhoudshapouran/react-native-ui-datepicker#128]
Basically, when I click on a date in the calendar, there's no visual indicator that a date was selected; looking at the console, i can confirm that the event is triggered. I'll attach a video showcasing the issue. Here's my code:
```js
import { Text, View } from "react-native";
import DateTimePicker from "react-native-ui-datepicker";

const MyAccountTab = () => {
  return (
    <View>
      <Text>My Account</Text>

      <DateTimePicker mode="single" onChange={(e) => console.log(e)} />
    </View>
  );
};

export default MyAccountTab;
```

https://github.com/user-attachments/assets/f36c98db-ee03-40f4-8dfe-23d34524aed9

**Comment by MaskoMasko** [comment]
That's because date value is not defined. If add date variable and set it on `onChange` event it's going to work. Something like this: 
`<DateTimePicker
        mode="single"
        onChange={e => setSelectedDate(e.date)}
        date={selectedDate}
  />`
