### ISSUE TITLE
Support date range

### ISSUE THREAD

**Issue by Levminer** [farhoudshapouran/react-native-ui-datepicker#21]
Hi!

Love the library so far, but I need to implement a range date picker.

Example:
![image](https://github.com/farhoudshapouran/react-native-ui-datepicker/assets/33373714/0f10f48a-1977-44d5-aa9a-e7251ce621ca)

**Comment by farhoudshapouran** [comment]
Hello @Levminer, Thanks for your interest in the library, I am working on this feature, it requires some refactoring, and I am trying to enable this option soon.

**Comment by farhoudshapouran** [comment]
> Have you implemented it yet?

I will enable the date range feature (and also multi-date selection) soon, I was so busy

**Comment by farhoudshapouran** [comment]
> Can you reply when you implemented date range please?

Sure, I'll keep you updated once I've integrated this feature into the datepicker.

**Comment by farhoudshapouran** [comment]
> Can you reply when you implemented date range please?

Hi @EdwardKashulsky `range` and `multiple` date modes added to the library, you can now define your preferred mode ;)

**Comment by Levminer** [comment]
> > Can you reply when you implemented date range please?
> 
> Hi @Levminer @EdwardKashulsky `range` and `multiple` date modes added to the library, you can now define your preferred mode ;)

Thanks for your work!
