### ISSUE TITLE
BUG: RangeError: invalid array length

### ISSUE THREAD

**Issue by kesylo** [farhoudshapouran/react-native-ui-datepicker#24]
Hello @farhoudshapouran 
I found this issue when using the library. I just discovered this component and it looks amazing. thanks for working on this. 
I followed your docs and the basic example but it crashes when you select a date. 

To reproduce:
- just use the basic example in your docs
- when the component renders, select a day. it will crash with this error: RangeError: invalid array length

I checked the code a bit, it looks like it comes from the **DaySelector** function in the **utils.ts** file

Please if you could look at this, it will be very helpful to me. 

Thanks

**Comment by kesylo** [comment]
By the way, I think the library is difficult to find on the web. I think it should have much more visibility

**Comment by farhoudshapouran** [comment]
Hi @kesylo I can't reproduce this error based on the basic example, but I'm trying to find what caused this error.

**Comment by farhoudshapouran** [comment]
> By the way, I think the library is difficult to find on the web. I think it should have much more visibility

Thank you for your interest in the library, yes you are right I have to work much more on visibility 👀

**Comment by kesylo** [comment]
Thats weird. I'll try to check if its a problem on my project maybe ? even though I have a pretty basic project. this is the error I get:
![ezgif com-video-to-gif](https://github.com/farhoudshapouran/react-native-ui-datepicker/assets/32457792/477fb78e-1f3c-4ba3-ab1d-24ce7afc3222)

**Comment by kesylo** [comment]
Btw I'm also using expo

**Comment by farhoudshapouran** [comment]
Based on the error message, I found that this problem is about time picker values, the values array must be checked before rendering, I opened a branch to fix it.

**Comment by kesylo** [comment]
Thanks for the quick fix but it caused another issue I think. Now this is what I get
![image](https://github.com/farhoudshapouran/react-native-ui-datepicker/assets/32457792/0f918f54-8f2f-4c07-a422-703b9cf7be5d)
