### ISSUE TITLE
Timepicker has performace issues

### ISSUE THREAD

**Issue by Elolawyn** [farhoudshapouran/react-native-ui-datepicker#47]
The spinning wheels work really bad. In case the animation add too many performance issues and problems, could they be changed to pressables with numbers like the Date section?

**Comment by farhoudshapouran** [comment]
Yes time picker has performance issues and I will change the time picker animation methods

**Comment by Elolawyn** [comment]
How about instead of the 2 spinning wheels that require complex calculations, just adding one vertical (or horizontal) ScrollView for each spinner with some fade effect on the sides.

**Comment by peterzanetti** [comment]
Time picker is still unusable, was this actually updated?

**Comment by NekodRider** [comment]
Same for me. The time picker is laggy on my Android/iOS phones, and only works fine on PC&iPad.

I think it might take time to look into it. Giving an option to use pressables instead is a good solution.

**Comment by mlhtnc** [comment]
It looks like PR did not solve the issue. Is there any improvement plan soon?

**Comment by farhoudshapouran** [comment]
Please upgrade to the latest version I changed the time picker component. https://github.com/farhoudshapouran/react-native-ui-datepicker/commit/e7d93648680d4f10ee5aec77244d633abe128254
