### ISSUE TITLE
Couldn't localize for Turkish

### ISSUE THREAD

**Issue by askmakdag** [farhoudshapouran/react-native-ui-datepicker#48]
I want to use the month names in Turkish. 
Giving `locale={'tr'} `didn't work.

**Comment by askmakdag** [comment]
`locale={require('dayjs/locale/tr')} ` fixed my issue. Thanks.

**Comment by farhoudshapouran** [comment]
It is better to import your desired locales in App.tsx (App.jsx):

`import 'dayjs/locale/tr'
import 'dayjs/locale/fr'
import 'dayjs/locale/de'`

and use your locale locale={'tr'} in DateTimePicker every where you want
