### ISSUE TITLE
selectedColor of Wheel should be able to be set via timePickerTextStyle

### ISSUE THREAD

**Issue by YaoHuiJi** [farhoudshapouran/react-native-ui-datepicker#55]
hi, we can't change the selectedColor of time wheel(it will always be 'black' which is not good for dark mode),  I think selectedColor of wheel should be able to be set via timePickerTextStyle.

I've submitted a [pull request](https://github.com/farhoudshapouran/react-native-ui-datepicker/pull/54), but I'm not sure if my changes are appropriate. Could you please review it?

Edit: It looks like I accidentally merged another pull request [#51](https://github.com/farhoudshapouran/react-native-ui-datepicker/pull/51) into this one before submitting. My apologies for the mix-up. Ths is another issue which I tried to solve in pr #51 ：

> If the count of day rows is not 6, the bottom blank area is too much when integrate the calendar in UI that has other views surround it.

I made some changes to reduce the bottom blank area when the count of day rows of current month is not 6, but also I'm not sure if my changes are appropriate, please review it.

Or just ignore my messy pull requests, and sovle the two issues in your more appropriate way ：）

**Comment by farhoudshapouran** [comment]
Yes you are right currently color of TimePicker text is defined inside the code and `timePickerTextStyle` don't change its color, we can add another property like `selectedColor` for time picker text color

**Comment by johnsimeroth** [comment]
Can this be merged in? I also would like this feature. It's a deal breaker in dark mode as-is.

**Comment by farhoudshapouran** [comment]
Please upgrade to the latest version I changed the time picker component. https://github.com/farhoudshapouran/react-native-ui-datepicker/commit/e7d93648680d4f10ee5aec77244d633abe128254
