### ISSUE TITLE
range issue

### ISSUE THREAD

**Issue by EdwardKashulsky** [farhoudshapouran/react-native-ui-datepicker#58]
For the range mode there are gaps in the selected range:

![IMG_1739](https://github.com/farhoudshapouran/react-native-ui-datepicker/assets/103606114/a1dce98a-531a-4f8b-a5c1-8fea54511e2a)

**Comment by farhoudshapouran** [comment]
I tested it on iOS, Android, and the web but I cannot reproduce this, can you reply with your code?

**Comment by hoax3** [comment]
Getting the same thing on IOS. On latest version and basically copying what you have done in the example App.tsx. Removed all styling and no avail. Seem to only be the last row of each month.

```
...
const [range, setRange] = useState({ startDate: undefined, endDate: undefined })
const today = dayjs()
...
<DateTimePicker mode='range' startDate={range.startDate} endDate={range.endDate} date={today} onChange={(params) => setRange(params)} />
...
```

**Comment by farhoudshapouran** [comment]
This bug was fixed https://github.com/farhoudshapouran/react-native-ui-datepicker/pull/87

**Comment by jtsimoes** [comment]
@farhoudshapouran Can you please publish a new version with this fix?
