### ISSUE TITLE
Console.log on mount 

### ISSUE THREAD

**Issue by z1Vinicius** [farhoudshapouran/react-native-ui-datepicker#70]
There is a "console.log" that emit when the component is mounted 

_farhoudshapouran/react-native-ui-datepicker/src/DateTimePicker.tsx_

Line 88 - **console.log(initialCalendarView);**

**Comment by farhoudshapouran** [comment]
I'll check it thank you

**Comment by farhoudshapouran** [comment]
This issue was resolved in v2.0.2
