### ISSUE TITLE
selected rangle  issue

### ISSUE THREAD

**Issue by VovaManzhula** [farhoudshapouran/react-native-ui-datepicker#73]
with the selected dates, for some reason the background is gray, although it should be blue, if you change the color of the selected dates, this strip may disappear, also on the screen you can see some gap and a strip near 1
![image](https://github.com/farhoudshapouran/react-native-ui-datepicker/assets/99676478/a0922261-43d3-4c80-9ccb-567322d5a3da)

if here is an example of my code
`
```typescript   
<DateTimePicker
		mode="range"
		startDate={startDateValue}
		endDate={endDateValue}
		onChange={({ startDate, endDate }) => {
		      console.log("picker params", startDate, endDate)
		      setStartDateValue(startDate)
		      setEndDateValue(endDate)
		}}
		todayContainerStyle={{ borderWidth: 0 }}
/>
```

**Comment by jtsimoes** [comment]
I'm having this issue too, at least on Android.
I notice that when `displayFullDays` is set to true, the gap disappears.

But still, there are some bugs visible, such as the range stripe losing the effect of attaching to the start/end day and some weird behavior when the end date is on the next month of the preview.

![image](https://github.com/farhoudshapouran/react-native-ui-datepicker/assets/34691647/fb3343a0-5794-4f7d-8b95-d2cfa20b26b2)

Btw I'm using Expo 50.0.7, React 18.2.0 and React Native 0.73.4 with NativeBase and the latest version of this package.

**Comment by farhoudshapouran** [comment]
I'll try to reproduce this bug and work on it thanks for reporting it

**Comment by parallaxpro** [comment]
![IMG_7B238B3ED2C6-1](https://github.com/farhoudshapouran/react-native-ui-datepicker/assets/64248086/7325e460-564b-4447-97b5-8d9661c15f02)
I am observing the current problem on iOS

**Comment by shuo-hiwintech** [comment]
+1

<img width="359" alt="image" src="https://github.com/user-attachments/assets/9005d800-9e0f-4ede-b06d-dd9f0118b698">
