### ISSUE TITLE
Select time issue

### ISSUE THREAD

**Issue by mauro-ferrario** [farhoudshapouran/react-native-ui-datepicker#74]
Hi added DateTimePicker in my project setting timePicker to true but when I try to change the time and move between the numberts all appears very slow and very hard to use. 
The same behaviour on Android simulator and real device.

**Comment by AndrijVasyliev** [comment]
Same issue here

**Comment by EmanuelOcampo** [comment]
same issue here

**Comment by mlhtnc** [comment]
I have got the same issue on emulator, not tested on a real device yet

**Comment by mlhtnc** [comment]
> I have got the same issue on emulator, not tested on a real device yet
> 
> Edit: When i got a build, it is faster enough imo.

On android real device, it responds scrolls after 2 seconds. It's almost impossible to use. Is there any performance improvement that I can apply?

**Comment by asergb-churon** [comment]
same issue for me, for web + android. my android phone is oppo reno5g 6 (2 years), my laptop is about 10 years old? but somehow my laptop handles this better than my phone, so i'm suspecting performance / optimization issues.

**Comment by kavinraju** [comment]
I am also facing the same issue. Its very slow in actual device (both android & iOS), but in simulator(iPhone 15) its working better than actual device, which is again little laggy. I have noticed few of the previous issues mentioning that this issue is fixed, but it's still persisting.

**Comment by fahdmk** [comment]
i have the same issue here still very laggy is there a solution?

**Comment by farhoudshapouran** [comment]
Please upgrade to the latest version I changed the time picker component. https://github.com/farhoudshapouran/react-native-ui-datepicker/commit/e7d93648680d4f10ee5aec77244d633abe128254

**Comment by Jhh910** [comment]
> Please upgrade to the latest version I changed the time picker component. [e7d9364](https://github.com/farhoudshapouran/react-native-ui-datepicker/commit/e7d93648680d4f10ee5aec77244d633abe128254)

 "react-native-ui-datepicker": "^2.0.3",    This is still the issue with the latest version

**Comment by Jhh910** [comment]
> same issue for me, for web + android. my android phone is oppo reno5g 6 (2 years), my laptop is about 10 years old? but somehow my laptop handles this better than my phone, so i'm suspecting performance / optimization issues.
> 
> probably why this flag isn't included in the documentation (only shown used in example code)
> 
> works very fine in chrome lmao
Did you solve it？
"react-native-ui-datepicker": "^2.0.3", This is still the issue with the latest version
