### ISSUE TITLE
Can't change the locale

### ISSUE THREAD

**Issue by poupsipoups** [farhoudshapouran/react-native-ui-datepicker#84]
I tried to change the locale in 'fr' and 'es' but nothing change. I also tried different format like 'FR', 'fr_FR' but nothing works.
I went to check the demo here : https://farhoudshapouran.github.io/react-native-ui-datepicker/ and event here when we click on locale buttons it doesn't change the language. 

Have someone the same mistake ? 

```javascript
<DateTimePicker
                    mode="single"
                    locale="fr"
                    firstDayOfWeek={1}
                    date={birthDate}
                    onChange={(response) => {
                      setBirthDate(new Date(response.date.toString()))
                      toggleDatePicker()
                    }}
                    selectedItemColor={colors.mainColors.mainColor}
/>
```

**Comment by timotismjntk** [comment]
add this on top, 
`require('dayjs/locale/fr');`

**Comment by poupsipoups** [comment]
thank you ! 😃
